/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfacciaGioco.java
 *
 * Created on 15-lug-2010, 13.00.26
 */
package avproject.gui;

import avproject.model.Locazione;

/**
 *
 * @author w4nder
 */
public class InterfacciaGioco extends javax.swing.JFrame {

    /** Creates new form InterfacciaGioco */
    public InterfacciaGioco(Locazione locazione, String difficoltaAttuale, String tipoVisualizzazioneAttuale, ControllerInterfacciaGioco controller) {
        this.controller = controller;
        this.locazione = locazione;
        this.difficoltaAttuale = difficoltaAttuale;
        this.tipoVisualizzazioneAttuale = tipoVisualizzazioneAttuale;
        initComponents();
        initParametrico();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelF = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NomeLocazione = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I N S O M N I S");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 22, 800, 570));
        setMinimumSize(new java.awt.Dimension(800, 570));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelF.setBackground(new java.awt.Color(51, 51, 51));
        jPanelF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButton1.setText("Carica");
        jButton1.setEnabled(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 3, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10));
        jButton2.setMnemonic('S');
        jButton2.setText("Salva");
        jButton2.setEnabled(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 3, -1, -1));
        jButton2.getAccessibleContext().setAccessibleDescription("Salva");

        NomeLocazione.setBackground(new java.awt.Color(0, 0, 0));
        NomeLocazione.setFont(new java.awt.Font("Tahoma", 1, 18));
        NomeLocazione.setForeground(new java.awt.Color(255, 255, 255));
        NomeLocazione.setText(locazione.getNome());
        jPanel1.add(NomeLocazione, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, -1, -1));

        jPanelF.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 770, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(locazione.getFileImmagineMappa())));
        jPanelF.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 55, 165, 165));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 50, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton6.setText("^");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 0, 50, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton7.setText("v");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, 50, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jButton8.setText(">");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 50, 30));

        jPanelF.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 235, 100, 100));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(locazione.getFileIllustrazione())));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 170));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(locazione.getNome() + "\n" + locazione.getDescrizione());
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setCaretPosition(0);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 560, 100));

        jPanelF.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 55, 580, 285));

        getContentPane().add(jPanelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        controller.setDirection("nord");
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        controller.setDirection("est");
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        controller.setDirection("sud");
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        controller.setDirection("ovest");
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        controller.confermaRisposta(jRadioButton1.isSelected(), jRadioButton2.isSelected(), jRadioButton3.isSelected(), jRadioButton4.isSelected());
        this.dispose();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        controller.visualizzaIndizio();
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        controller.cambiaVisualizzazione();
        this.dispose();
    }

    private void initParametrico() {
        if (locazione.getEnigma() != null && !locazione.getEnigma().isGiaRisolto() && locazione.getEnigma().getNumeroRisposteErrate() < 2) {
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jButton9 = new javax.swing.JButton();
            jPanel4 = new javax.swing.JPanel();
            jPanel5 = new javax.swing.JPanel();
            jRadioButton1 = new javax.swing.JRadioButton();
            jRadioButton2 = new javax.swing.JRadioButton();
            jRadioButton3 = new javax.swing.JRadioButton();
            jRadioButton4 = new javax.swing.JRadioButton();
            jScrollPane2 = new javax.swing.JScrollPane();

            jPanel4.setBackground(new java.awt.Color(0, 0, 0));
            jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
            jPanel4.setForeground(new java.awt.Color(255, 255, 255));
            jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
            jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Risposte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
            jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
            jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

            jPanel5.setBackground(new java.awt.Color(0, 0, 0));
            jPanel5.setForeground(new java.awt.Color(255, 255, 255));
            jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.PAGE_AXIS));

            jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
            buttonGroup1.add(jRadioButton1);
            jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 13));
            jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
            jPanel5.add(jRadioButton1);

            jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
            buttonGroup1.add(jRadioButton2);
            jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 13));
            jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
            jPanel5.add(jRadioButton2);

            jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
            buttonGroup1.add(jRadioButton3);
            jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 13));
            jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
            jPanel5.add(jRadioButton3);

            jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
            buttonGroup1.add(jRadioButton4);
            jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 13));
            jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
            jPanel5.add(jRadioButton4);

            jScrollPane2.setViewportView(jPanel5);

            jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 10, 300, 130));

            jButton3.setText("?");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

            jButton9.setText("Cambia Stile");
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton9ActionPerformed(evt);
                }
            });
            jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

            jButton4.setText("Conferma");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });
            jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 150, -1, -1));

            jPanelF.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, 770, 190));

            if (difficoltaAttuale.equals("facile")) {
                if (tipoVisualizzazioneAttuale.equals("testuale")) {
                    javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
                    jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
                    jScrollPane3.setBorder(null);
                    jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
                    jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

                    javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
                    jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
                    jTextArea2.setColumns(20);
                    jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
                    jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
                    jTextArea2.setRows(5);
                    jTextArea2.setLineWrap(true);
                    jTextArea2.setWrapStyleWord(true);
                    jTextArea2.setText(locazione.getEnigma().getTestoEnigmaFacile());
                    jTextArea2.setEditable(false);
                    jTextArea2.setCaretPosition(0);
                    jScrollPane3.setViewportView(jTextArea2);

                    jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 425, 170));
                } else {
                    javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(locazione.getEnigma().getFileImmagineFacile())));
                    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 415, 170));
                }
                jRadioButton1.setText(locazione.getEnigma().getRisposteFacili().get(0));
                jRadioButton2.setText(locazione.getEnigma().getRisposteFacili().get(1));
                jRadioButton3.setText(locazione.getEnigma().getRisposteFacili().get(2));
                jRadioButton4.setText(locazione.getEnigma().getRisposteFacili().get(3));
            } else if (difficoltaAttuale.equals("medio")) {
                if (tipoVisualizzazioneAttuale.equals("testuale")) {
                    javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
                    jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
                    jScrollPane3.setBorder(null);
                    jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
                    jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

                    javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
                    jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
                    jTextArea2.setColumns(20);
                    jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
                    jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
                    jTextArea2.setRows(5);
                    jTextArea2.setLineWrap(true);
                    jTextArea2.setWrapStyleWord(true);
                    jTextArea2.setText(locazione.getEnigma().getTestoEnigmaMedio());
                    jTextArea2.setCaretPosition(0);
                    jTextArea2.setEditable(false);
                    jScrollPane3.setViewportView(jTextArea2);

                    jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 425, 170));
                } else {
                    javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(locazione.getEnigma().getFileImmagineMedio())));
                    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 415, 170));
                }
                jRadioButton1.setText(locazione.getEnigma().getRisposteMedia().get(0));
                jRadioButton2.setText(locazione.getEnigma().getRisposteMedia().get(1));
                jRadioButton3.setText(locazione.getEnigma().getRisposteMedia().get(2));
                jRadioButton4.setText(locazione.getEnigma().getRisposteMedia().get(3));
            } else {
                if (tipoVisualizzazioneAttuale.equals("testuale")) {
                    javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
                    jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
                    jScrollPane3.setBorder(null);
                    jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
                    jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

                    javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
                    jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
                    jTextArea2.setColumns(20);
                    jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
                    jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
                    jTextArea2.setRows(5);
                    jTextArea2.setLineWrap(true);
                    jTextArea2.setWrapStyleWord(true);
                    jTextArea2.setText(locazione.getEnigma().getTestoEnigmaDifficile());
                    jTextArea2.setCaretPosition(0);
                    jTextArea2.setEditable(false);
                    jScrollPane3.setViewportView(jTextArea2);

                    jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 425, 170));
                } else {
                    javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(locazione.getEnigma().getFileImmagineDifficile())));
                    jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 415, 170));
                }
                jRadioButton1.setText(locazione.getEnigma().getRisposteDifficili().get(0));
                jRadioButton2.setText(locazione.getEnigma().getRisposteDifficili().get(1));
                jRadioButton3.setText(locazione.getEnigma().getRisposteDifficili().get(2));
                jRadioButton4.setText(locazione.getEnigma().getRisposteDifficili().get(3));
            }
        } else {
            if (locazione.getEnigma() != null) {

                jPanel4 = new javax.swing.JPanel();

                jPanel4.setBackground(new java.awt.Color(0, 0, 0));
                jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
                jPanel4.setForeground(new java.awt.Color(255, 255, 255));
                jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanelF.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 350, 770, 190));

                if (locazione.getEnigma().getNumeroRisposteErrate() >= 2) {
                    javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
                    jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
                    jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
                    jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
                    jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

                    javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
                    jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
                    jTextArea2.setColumns(20);
                    jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
                    jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
                    jTextArea2.setRows(5);
                    jTextArea2.setLineWrap(true);
                    jTextArea2.setWrapStyleWord(true);
                    jTextArea2.setText("Troppi errori commessi, impossibile risolvere l'enigma");
                    jTextArea2.setCaretPosition(0);
                    jTextArea2.setEditable(false);
                    jScrollPane3.setViewportView(jTextArea2);

                    jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 425, 170));
                } else if (locazione.getEnigma().isGiaRisolto()) {
                    javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
                    jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
                    jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
                    jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
                    jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

                    javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
                    jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
                    jTextArea2.setColumns(20);
                    jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
                    jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
                    jTextArea2.setRows(5);
                    jTextArea2.setLineWrap(true);
                    jTextArea2.setWrapStyleWord(true);
                    jTextArea2.setText("Enigma già risolto correttamente");
                    jTextArea2.setCaretPosition(0);
                    jTextArea2.setEditable(false);
                    jScrollPane3.setViewportView(jTextArea2);

                    jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 425, 170));
                }
            }
        }
        if (locazione.getLocazioneNord() == null) {
            jButton6.setEnabled(false);
        }
        if (locazione.getLocazioneSud() == null) {
            jButton7.setEnabled(false);
        }
        if (locazione.getLocazioneOvest() == null) {
            jButton5.setEnabled(false);
        }
        if (locazione.getLocazioneEst() == null) {
            jButton8.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeLocazione;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane2;
    private Locazione locazione;
    private String difficoltaAttuale;
    private String tipoVisualizzazioneAttuale;
    private ControllerInterfacciaGioco controller;
}
