/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfacciaQuestionario.java
 *
 * Created on 15-lug-2010, 13.32.21
 */

package avproject.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Gianni
 */
public class InterfacciaQuestionario extends javax.swing.JDialog {

    /** Creates new form InterfacciaQuestionario */
    public InterfacciaQuestionario(ControllerInterfacciaQuestionario controller) {
        this.controller = controller;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpDomanda1 = new javax.swing.ButtonGroup();
        btnGrpDomanda2 = new javax.swing.ButtonGroup();
        btnGrpDomanda4 = new javax.swing.ButtonGroup();
        btnGrpDomanda7 = new javax.swing.ButtonGroup();
        btnGrpIndovinelloFigura = new javax.swing.ButtonGroup();
        btnGrpIndovinelloParola = new javax.swing.ButtonGroup();
        pnlIstruzione = new javax.swing.JPanel();
        lblInformatica = new javax.swing.JLabel();
        lblIstruzione = new javax.swing.JLabel();
        rdBtnScuolaSuperiore = new javax.swing.JRadioButton();
        rdBtnSiInformatica = new javax.swing.JRadioButton();
        rdBtnNoInformatica = new javax.swing.JRadioButton();
        rdBtnUniversita = new javax.swing.JRadioButton();
        pnlTool = new javax.swing.JPanel();
        chBoxEditorTesto = new javax.swing.JCheckBox();
        chBoxDBMS = new javax.swing.JCheckBox();
        chBoxIDE = new javax.swing.JCheckBox();
        lblTool = new javax.swing.JLabel();
        pnlGiaGiocato = new javax.swing.JPanel();
        lblGiaGiocato = new javax.swing.JLabel();
        rdBtnSiGiaGiocato = new javax.swing.JRadioButton();
        rdBtnNoGiaGiocato = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlIndovinelloFigura = new javax.swing.JPanel();
        lblImmagine = new javax.swing.JLabel();
        lblFigura = new javax.swing.JLabel();
        rdBtnFigura1 = new javax.swing.JRadioButton();
        rdBtnFigura2 = new javax.swing.JRadioButton();
        rdBtnFigura3 = new javax.swing.JRadioButton();
        rdBtnFigura4 = new javax.swing.JRadioButton();
        pnlIndovinelloParola = new javax.swing.JPanel();
        lblParola = new javax.swing.JLabel();
        rdBtnParola1 = new javax.swing.JRadioButton();
        rdBtnParola2 = new javax.swing.JRadioButton();
        rdBtnParola3 = new javax.swing.JRadioButton();
        rdBtnParola4 = new javax.swing.JRadioButton();
        pnlPreferenza = new javax.swing.JPanel();
        lblIndovinelloPreferito = new javax.swing.JLabel();
        rdBtnGrafico = new javax.swing.JRadioButton();
        rdBtnTestuale = new javax.swing.JRadioButton();
        btnConferma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("I N S O M N I S - Questionario");
        setModal(true);

        pnlIstruzione.setBorder(javax.swing.BorderFactory.createTitledBorder("Istruzione"));

        lblInformatica.setText("Hai mai studiato Informatica?");

        lblIstruzione.setText("A che grado di istruzione?");

        btnGrpDomanda2.add(rdBtnScuolaSuperiore);
        rdBtnScuolaSuperiore.setText("Scuola Superiore");
        rdBtnScuolaSuperiore.setEnabled(false);
        rdBtnScuolaSuperiore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnScuolaSuperioreActionPerformed(evt);
            }
        });

        btnGrpDomanda1.add(rdBtnSiInformatica);
        rdBtnSiInformatica.setText("Si");
        rdBtnSiInformatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnSiInformaticaActionPerformed(evt);
            }
        });

        btnGrpDomanda1.add(rdBtnNoInformatica);
        rdBtnNoInformatica.setText("No");
        rdBtnNoInformatica.setActionCommand("no");
        rdBtnNoInformatica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnNoInformaticaActionPerformed(evt);
            }
        });

        btnGrpDomanda2.add(rdBtnUniversita);
        rdBtnUniversita.setText("Università");
        rdBtnUniversita.setEnabled(false);
        rdBtnUniversita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnUniversitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlIstruzioneLayout = new javax.swing.GroupLayout(pnlIstruzione);
        pnlIstruzione.setLayout(pnlIstruzioneLayout);
        pnlIstruzioneLayout.setHorizontalGroup(
            pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIstruzioneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformatica, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIstruzione))
                .addGap(18, 18, 18)
                .addGroup(pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIstruzioneLayout.createSequentialGroup()
                        .addComponent(rdBtnSiInformatica)
                        .addGap(90, 90, 90)
                        .addComponent(rdBtnNoInformatica))
                    .addGroup(pnlIstruzioneLayout.createSequentialGroup()
                        .addComponent(rdBtnScuolaSuperiore)
                        .addGap(18, 18, 18)
                        .addComponent(rdBtnUniversita)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlIstruzioneLayout.setVerticalGroup(
            pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIstruzioneLayout.createSequentialGroup()
                .addGroup(pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformatica)
                    .addGroup(pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdBtnSiInformatica)
                        .addComponent(rdBtnNoInformatica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIstruzione)
                    .addGroup(pnlIstruzioneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdBtnScuolaSuperiore)
                        .addComponent(rdBtnUniversita))))
        );

        pnlTool.setBorder(javax.swing.BorderFactory.createTitledBorder("Tool"));

        chBoxEditorTesto.setText("Editor di testo");
        chBoxEditorTesto.setEnabled(false);

        chBoxDBMS.setText("DBMS");
        chBoxDBMS.setEnabled(false);

        chBoxIDE.setText("Compilatore (o ambiente di sviluppo integrato)");
        chBoxIDE.setEnabled(false);

        lblTool.setText("<html>Seleziona il/i tool che hai utilizzato <br> almeno una volta:</html>");

        javax.swing.GroupLayout pnlToolLayout = new javax.swing.GroupLayout(pnlTool);
        pnlTool.setLayout(pnlToolLayout);
        pnlToolLayout.setHorizontalGroup(
            pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTool, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chBoxIDE)
                    .addComponent(chBoxEditorTesto)
                    .addComponent(chBoxDBMS))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnlToolLayout.setVerticalGroup(
            pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolLayout.createSequentialGroup()
                .addGroup(pnlToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlToolLayout.createSequentialGroup()
                        .addComponent(chBoxEditorTesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chBoxDBMS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chBoxIDE))
                    .addComponent(lblTool, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlGiaGiocato.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilizzi precedenti"));

        lblGiaGiocato.setText("Hai già giocato a questo gioco?");

        btnGrpDomanda4.add(rdBtnSiGiaGiocato);
        rdBtnSiGiaGiocato.setText("Si");
        rdBtnSiGiaGiocato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnSiGiaGiocatoActionPerformed(evt);
            }
        });

        btnGrpDomanda4.add(rdBtnNoGiaGiocato);
        rdBtnNoGiaGiocato.setText("No");
        rdBtnNoGiaGiocato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnNoGiaGiocatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGiaGiocatoLayout = new javax.swing.GroupLayout(pnlGiaGiocato);
        pnlGiaGiocato.setLayout(pnlGiaGiocatoLayout);
        pnlGiaGiocatoLayout.setHorizontalGroup(
            pnlGiaGiocatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaGiocatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGiaGiocato)
                .addGap(40, 40, 40)
                .addComponent(rdBtnSiGiaGiocato)
                .addGap(89, 89, 89)
                .addComponent(rdBtnNoGiaGiocato)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlGiaGiocatoLayout.setVerticalGroup(
            pnlGiaGiocatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiaGiocatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblGiaGiocato)
                .addComponent(rdBtnSiGiaGiocato)
                .addComponent(rdBtnNoGiaGiocato))
        );

        pnlIndovinelloFigura.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avproject/images/indovinello_grafico.png"))); // NOI18N

        lblFigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFigura.setText("Scegli la figura giusta tra le 4 proposte:");

        btnGrpIndovinelloFigura.add(rdBtnFigura1);
        rdBtnFigura1.setText("1");
        rdBtnFigura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnFigura1ActionPerformed(evt);
            }
        });

        btnGrpIndovinelloFigura.add(rdBtnFigura2);
        rdBtnFigura2.setText("2");

        btnGrpIndovinelloFigura.add(rdBtnFigura3);
        rdBtnFigura3.setText("3");

        btnGrpIndovinelloFigura.add(rdBtnFigura4);
        rdBtnFigura4.setText("4");

        javax.swing.GroupLayout pnlIndovinelloFiguraLayout = new javax.swing.GroupLayout(pnlIndovinelloFigura);
        pnlIndovinelloFigura.setLayout(pnlIndovinelloFiguraLayout);
        pnlIndovinelloFiguraLayout.setHorizontalGroup(
            pnlIndovinelloFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIndovinelloFiguraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblImmagine, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addComponent(lblFigura, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addGroup(pnlIndovinelloFiguraLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlIndovinelloFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtnFigura1)
                    .addComponent(rdBtnFigura2))
                .addGap(44, 44, 44)
                .addGroup(pnlIndovinelloFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdBtnFigura4)
                    .addComponent(rdBtnFigura3))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pnlIndovinelloFiguraLayout.setVerticalGroup(
            pnlIndovinelloFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIndovinelloFiguraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImmagine, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIndovinelloFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnFigura1)
                    .addComponent(rdBtnFigura3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIndovinelloFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnFigura2)
                    .addComponent(rdBtnFigura4)))
        );

        pnlIndovinelloParola.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlIndovinelloParola.setPreferredSize(new java.awt.Dimension(274, 386));

        lblParola.setText("<html> Trova la parola da scartare: <br> <ol type=\"1\"> <li>titopa <li>chiacciuo <li>sdocella <li>efragnatu </ol> </html>");

        btnGrpIndovinelloParola.add(rdBtnParola1);
        rdBtnParola1.setText("1");

        btnGrpIndovinelloParola.add(rdBtnParola2);
        rdBtnParola2.setText("2");

        btnGrpIndovinelloParola.add(rdBtnParola3);
        rdBtnParola3.setText("3");

        btnGrpIndovinelloParola.add(rdBtnParola4);
        rdBtnParola4.setText("4");

        javax.swing.GroupLayout pnlIndovinelloParolaLayout = new javax.swing.GroupLayout(pnlIndovinelloParola);
        pnlIndovinelloParola.setLayout(pnlIndovinelloParolaLayout);
        pnlIndovinelloParolaLayout.setHorizontalGroup(
            pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIndovinelloParolaLayout.createSequentialGroup()
                .addGroup(pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIndovinelloParolaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblParola, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                    .addGroup(pnlIndovinelloParolaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnParola1)
                            .addComponent(rdBtnParola2))
                        .addGap(44, 44, 44)
                        .addGroup(pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdBtnParola4)
                            .addComponent(rdBtnParola3))))
                .addContainerGap())
        );
        pnlIndovinelloParolaLayout.setVerticalGroup(
            pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIndovinelloParolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParola, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnParola1)
                    .addComponent(rdBtnParola3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIndovinelloParolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdBtnParola2)
                    .addComponent(rdBtnParola4))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pnlPreferenza.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblIndovinelloPreferito.setText("<html>Quale dei due indovinelli<br> ti è piaciuto di più?</html>");

        btnGrpDomanda7.add(rdBtnGrafico);
        rdBtnGrafico.setText("Grafico");

        btnGrpDomanda7.add(rdBtnTestuale);
        rdBtnTestuale.setText("Testuale");

        javax.swing.GroupLayout pnlPreferenzaLayout = new javax.swing.GroupLayout(pnlPreferenza);
        pnlPreferenza.setLayout(pnlPreferenzaLayout);
        pnlPreferenzaLayout.setHorizontalGroup(
            pnlPreferenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreferenzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIndovinelloPreferito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(rdBtnGrafico)
                .addGap(58, 58, 58)
                .addComponent(rdBtnTestuale)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        pnlPreferenzaLayout.setVerticalGroup(
            pnlPreferenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreferenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rdBtnTestuale)
                .addComponent(lblIndovinelloPreferito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rdBtnGrafico))
        );

        btnConferma.setText("Conferma");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTool, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlIndovinelloFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pnlIndovinelloParola, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                    .addComponent(pnlIstruzione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGiaGiocato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPreferenza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnConferma)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlIstruzione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlGiaGiocato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlIndovinelloParola, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlIndovinelloFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(pnlPreferenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConferma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnSiInformaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnSiInformaticaActionPerformed
        // TODO add your handling code here:
        rdBtnScuolaSuperiore.setEnabled(true);
        rdBtnUniversita.setEnabled(true);
        chBoxEditorTesto.setEnabled(false);
        chBoxDBMS.setEnabled(false);
        chBoxIDE.setEnabled(false);
    }//GEN-LAST:event_rdBtnSiInformaticaActionPerformed

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        // TODO add your handling code here:
        if (!rdBtnSiInformatica.isSelected() && !rdBtnNoInformatica.isSelected()) {
            JOptionPane.showMessageDialog(this, "Rispondi alla domanda \"Hai mai studiato informatica?\"");
            return;
        } else {
            if (rdBtnSiInformatica.isSelected()) {
                if (!rdBtnUniversita.isSelected() && !rdBtnScuolaSuperiore.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Rispondi alla domanda \"A che grado di istruzione?\"");
                    return;
                }
            }
        }
        if (!rdBtnSiGiaGiocato.isSelected() && !rdBtnNoGiaGiocato.isSelected()) {
            JOptionPane.showMessageDialog(this, "Rispondi alla domanda \"Hai già giocato a questo gioco?\"");
            return;
        }
        if (!rdBtnFigura1.isSelected() && !rdBtnFigura2.isSelected() && !rdBtnFigura3.isSelected() && !rdBtnFigura4.isSelected()) {
            JOptionPane.showMessageDialog(this, "Rispondi all'indovinello grafico");
            return;
        }
        if (!rdBtnParola1.isSelected() && !rdBtnParola2.isSelected() && !rdBtnParola3.isSelected() && !rdBtnParola4.isSelected()) {
            JOptionPane.showMessageDialog(this, "Rispondi all'indovinello testuale");
            return;
        }
        if (!rdBtnGrafico.isSelected() && !rdBtnTestuale.isSelected()) {
            JOptionPane.showMessageDialog(this, "Rispondi alla domanda \"Quale dei due indovinelli ti è piaciuto di più?\"");
            return;
        }
        this.dispose();
        controller.setRisultatiQuestionario(rdBtnSiInformatica.isSelected(),
                                            rdBtnScuolaSuperiore.isSelected(),
                                            chBoxEditorTesto.isSelected(),
                                            chBoxDBMS.isSelected(),
                                            chBoxIDE.isSelected(),
                                            rdBtnSiGiaGiocato.isSelected(),
                                            rdBtnFigura4.isSelected(),
                                            rdBtnParola4.isSelected(),
                                            rdBtnGrafico.isSelected());

    }//GEN-LAST:event_btnConfermaActionPerformed

    private void rdBtnNoInformaticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnNoInformaticaActionPerformed
        // TODO add your handling code here:
        chBoxEditorTesto.setEnabled(true);
        chBoxDBMS.setEnabled(true);
        chBoxIDE.setEnabled(true);
        rdBtnScuolaSuperiore.setEnabled(false);
        rdBtnUniversita.setEnabled(false);

    }//GEN-LAST:event_rdBtnNoInformaticaActionPerformed

    private void rdBtnScuolaSuperioreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnScuolaSuperioreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnScuolaSuperioreActionPerformed

    private void rdBtnUniversitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnUniversitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnUniversitaActionPerformed

    private void rdBtnSiGiaGiocatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnSiGiaGiocatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnSiGiaGiocatoActionPerformed

    private void rdBtnNoGiaGiocatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnNoGiaGiocatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnNoGiaGiocatoActionPerformed

    private void rdBtnFigura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnFigura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtnFigura1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.ButtonGroup btnGrpDomanda1;
    private javax.swing.ButtonGroup btnGrpDomanda2;
    private javax.swing.ButtonGroup btnGrpDomanda4;
    private javax.swing.ButtonGroup btnGrpDomanda7;
    private javax.swing.ButtonGroup btnGrpIndovinelloFigura;
    private javax.swing.ButtonGroup btnGrpIndovinelloParola;
    private javax.swing.JCheckBox chBoxDBMS;
    private javax.swing.JCheckBox chBoxEditorTesto;
    private javax.swing.JCheckBox chBoxIDE;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFigura;
    private javax.swing.JLabel lblGiaGiocato;
    private javax.swing.JLabel lblImmagine;
    private javax.swing.JLabel lblIndovinelloPreferito;
    private javax.swing.JLabel lblInformatica;
    private javax.swing.JLabel lblIstruzione;
    private javax.swing.JLabel lblParola;
    private javax.swing.JLabel lblTool;
    private javax.swing.JPanel pnlGiaGiocato;
    private javax.swing.JPanel pnlIndovinelloFigura;
    private javax.swing.JPanel pnlIndovinelloParola;
    private javax.swing.JPanel pnlIstruzione;
    private javax.swing.JPanel pnlPreferenza;
    private javax.swing.JPanel pnlTool;
    private javax.swing.JRadioButton rdBtnFigura1;
    private javax.swing.JRadioButton rdBtnFigura2;
    private javax.swing.JRadioButton rdBtnFigura3;
    private javax.swing.JRadioButton rdBtnFigura4;
    private javax.swing.JRadioButton rdBtnGrafico;
    private javax.swing.JRadioButton rdBtnNoGiaGiocato;
    private javax.swing.JRadioButton rdBtnNoInformatica;
    private javax.swing.JRadioButton rdBtnParola1;
    private javax.swing.JRadioButton rdBtnParola2;
    private javax.swing.JRadioButton rdBtnParola3;
    private javax.swing.JRadioButton rdBtnParola4;
    private javax.swing.JRadioButton rdBtnScuolaSuperiore;
    private javax.swing.JRadioButton rdBtnSiGiaGiocato;
    private javax.swing.JRadioButton rdBtnSiInformatica;
    private javax.swing.JRadioButton rdBtnTestuale;
    private javax.swing.JRadioButton rdBtnUniversita;
    // End of variables declaration//GEN-END:variables
    private ControllerInterfacciaQuestionario controller;
}
